version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/Tasks/Common"
      - "/Tasks/InstallArgoCDCLI"
      - "/Tasks/InstallCheckmarxOneCLI"
      - "/Tasks/InstallDatabricksCLI"
      - "/Tasks/InstallHashicorpSentinelCLI"
      - "/Tasks/InstallOpenTofuCLI"
      - "/Tasks/InstallPackerCLI"
      - "/Tasks/InstallWizCLI"
    schedule:
      interval: "weekly"
